### PR TITLE
Nodejs 18 and Java 17

### PR DESCRIPTION
**Pull request by vinc3nz**
Nodejs does now also chooses the newest version automatically

### CODE REVIEW

**Comment by DEV-DIBSTER** [comment]
Changes look alright at a quick glance, will check it out when I get home. Has this been testing?

**Comment by djohts** [comment]
> Changes look alright at a quick glance, will check it out when I get home. Has this been testing?

why shouldnt it work kek

**Comment by vinc3nz** [comment]
No, i havent tested this. I currently have no pterodactyl-vm on my server. But i also see no problem here.

**Comment by danielpmc** [comment]
Tested, and marged

**Comment by danielpmc** [comment]
image
just waiting on docker hub to build image ready to release

**Comment by danielpmc** [comment]
Failed because of java on dockers side.

**Comment by DEV-DIBSTER** [comment]
> > Changes look alright at a quick glance, will check it out when I get home. Has this been testing?
> 
> why shouldnt it work kek

Anything is possible during actual live testing, it's always better to check and verify.

**Comment by DEV-DIBSTER** [comment]
> Tested, and marged

Merged*.

**Comment by danielpmc** [comment]
Fails to build publicly due to java17 not found

**Pull request merged**
