### PR TITLE
Add OpenJDK 17 LTS.

### PR DESCRIPTION
**Pull request by Tweak4141**

### CODE REVIEW

**Comment by djohts** [comment]
software-properties-common is already installed on line 7

**Comment by Tweak4141** [comment]
> software-properties-common is already installed on line 7

Ah I see, thank you. It was there previously, I just repositioned it.

**Comment by danielpmc** [comment]
2023-01-26T20:27:09Z #11 5.525 /bin/sh: 1: wget: not found

**Comment by DEV-DIBSTER** [comment]
Curl should probably do the trick.

**Comment by danielpmc** [comment]
> Curl should probably do the trick.

Done after i added wget in latest commit, Build completed without errors

**Pull request merged**
