### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by PadowYT2**

### CODE REVIEW

**Comment by djohts** [comment]
u should replace 2020 with 2021 afaik, not just from - to

**Comment by Xcyth** [comment]
this is the most useless pr i have seen in a while, you could try making some worthwhile prs rather than making dumb prs

**Comment by Sliden101** [comment]
i only cum inside anime girls and updating licenses are for pussies

**Comment by PadowYT2** [comment]
what the

**Pull request closed without merging**
